name: Deploy the project to AWS

on:
   push:
      branches:
         - main

jobs: 
  build: 
    name: build and deploy the image to AWS
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Configure the AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-east-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2 

      - name: Build and Push Docker Image
        id: build
        env:
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          ECR_REPOSITORY: node-todo-api
          IMAGE_TAG: ${{ github.sha }}
          
         
         
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
         
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .aws/task-definition.json
          container-name: api_app
          image: ${{steps.build.outputs.image}}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: node-todo-service
          cluster: ecs_cluster
          wait-for-service-stability: true